In [2]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from imblearn.over_sampling import RandomOverSampler

In [3]:
dataset_path = r"C:/Users/user/Desktop/data/sleepapi/app/data/Wearable_Tech_Sleep_Stress_Dataset.csv"

def get_dataframe(path: str = dataset_path) -> pd.DataFrame:
    df = pd.read_csv(path)
    return df

In [4]:
df = get_dataframe()
new_cols = []
for column in df.columns:
    new_cols.append(column.replace(' ', '_').lower())

df.columns = new_cols

In [18]:
df.drop(columns=['user_id'], inplace=True)
df

,age,gender,physical_activity_level,diet_type,bmi,caffeine_intake_mg,water_intake_liters,screen_time_hours,daily_steps,calories_burned,resting_heart_rate,daily_sleep_hours,deep_sleep_hours,sleep_quality_score,daily_stress_level
0,56,Female,Low,Healthy,25.1,99.0,1.6,3.9,4731,1697,74.0,6.6,1.5,4.0,Low
1,69,Male,Low,Average,25.8,104.0,2.2,3.9,4440,1377,70.0,8.0,2.4,5.3,Low
2,46,Male,Low,Average,24.0,188.0,1.4,5.5,5023,1289,72.0,8.2,1.9,5.0,Medium
3,32,Female,Medium,Healthy,25.5,124.0,3.1,9.8,6082,1683,69.0,7.4,2.5,3.9,Low
4,60,Male,Medium,Unhealthy,NaN,0.0,2.4,5.3,7285,1621,73.0,7.9,2.2,5.2,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,55,Female,Medium,Average,20.9,327.0,1.7,5.7,8336,1555,61.0,6.3,1.9,4.1,Low
9996,51,Female,Medium,Healthy,21.9,210.0,1.3,8.7,10170,1671,65.0,5.0,1.3,3.3,Low
9997,57,Male,Low,Average,32.9,227.0,2.8,14.0,1000,1592,89.0,6.4,1.7,2.8,High
9998,64,Female,Low,Average,18.4,222.0,2.3,7.3,4206,1429,65.0,6.6,2.2,4.0,Medium
9999,32,Female,Low,Average,20.0,197.0,1.6,8.7,2746,1240,68.0,6.1,1.4,3.4,Medium

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      10000 non-null  int64
 1   gender                   10000 non-null  object
 2   physical_activity_level  10000 non-null  object
 3   diet_type                10000 non-null  object
 4   bmi                      9790 non-null   float64
 5   caffeine_intake_mg       9794 non-null   float64
 6   water_intake_liters      10000 non-null  float64
 7   screen_time_hours        10000 non-null  float64
 8   daily_steps              10000 non-null  int64
 9   calories_burned          10000 non-null  int64
 10  resting_heart_rate       9781 non-null   float64
 11  daily_sleep_hours        9810 non-null   float64
 12  deep_sleep_hours         10000 non-null  float64
 13  sleep_quality_score      10000 non-null  float64
 14  daily_stress_level       10000 non-null  object
dtypes: float64(8), int64(3), object(4)
memory usage: 1.1+ MB

In [7]:
df.describe()

,age,bmi,caffeine_intake_mg,water_intake_liters,screen_time_hours,daily_steps,calories_burned,resting_heart_rate,daily_sleep_hours,deep_sleep_hours,sleep_quality_score
count,10000.000000,9790.000000,9794.000000,10000.000000,10000.000000,10000.000000,10000.000000,9781.000000,9810.000000,10000.000000,10000.000000
mean,43.539400,25.087406,207.365224,2.502550,7.060990,7963.857000,1573.986300,66.944177,6.957951,1.750610,4.170080
std,14.911636,3.905276,137.681368,0.802058,2.443689,4021.490815,320.153851,8.450527,0.907726,0.467773,0.914011
min,18.000000,17.500000,0.000000,0.500000,2.000000,1000.000000,491.000000,50.000000,3.500000,0.700000,1.000000
25%,31.000000,22.300000,100.000000,2.000000,5.300000,4919.500000,1354.000000,61.000000,6.300000,1.400000,3.500000
50%,43.000000,25.100000,201.000000,2.500000,7.100000,7396.500000,1561.000000,67.000000,7.000000,1.700000,4.200000
75%,56.000000,27.800000,303.000000,3.000000,8.700000,10119.250000,1786.000000,73.000000,7.600000,2.100000,4.800000
max,69.000000,38.000000,730.000000,5.000000,14.000000,23451.000000,2901.000000,95.000000,10.900000,3.400000,7.500000

In [8]:
df.daily_stress_level.value_counts()

daily_stress_level
Low       5789
Medium    3786
High       425
Name: count, dtype: int64

In [9]:
df.to_csv('C:/Users/user/Desktop/data/sleepapi/app/data/reSS.csv', index=False)