In [ ]:
import seaborn as sns
import pandas as pd
import os
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from imblearn.over_sampling import RandomOverSampler

In [ ]:
dataset_path = r"app/data/Wearable_Tech_Sleep_Stress_Dataset.csv"
def get_dataframe(path: str = dataset_path) -> pd.DataFrame:
    df = pd.read_csv(path)
    return df

In [ ]:
df = get_dataframe(dataset_path)
new_cols = []
for column in df.columns:
    new_cols.append(column.replace(' ', '_').lower())
df.columns = new_cols
df.drop(columns=['user_id'], inplace=True)

here we will do a little feature engineering so we have a "new" feature that shows how far from perfect sleep

In [40]:
df['sleep_deviation'] = (8 - df['daily_sleep_hours']).abs()
df = df.drop(columns=['daily_sleep_hours'])

In [41]:
df

,age,gender,physical_activity_level,diet_type,bmi,caffeine_intake_mg,water_intake_liters,screen_time_hours,daily_steps,calories_burned,resting_heart_rate,deep_sleep_hours,sleep_quality_score,daily_stress_level,sleep_deviation
0,56,Female,Low,Healthy,25.1,99.0,1.6,3.9,4731,1697,74.0,1.5,4.0,Low,1.4
1,69,Male,Low,Average,25.8,104.0,2.2,3.9,4440,1377,70.0,2.4,5.3,Low,0.0
2,46,Male,Low,Average,24.0,188.0,1.4,5.5,5023,1289,72.0,1.9,5.0,Medium,0.2
3,32,Female,Medium,Healthy,25.5,124.0,3.1,9.8,6082,1683,69.0,2.5,3.9,Low,0.6
4,60,Male,Medium,Unhealthy,NaN,0.0,2.4,5.3,7285,1621,73.0,2.2,5.2,Low,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,55,Female,Medium,Average,20.9,327.0,1.7,5.7,8336,1555,61.0,1.9,4.1,Low,1.7
9996,51,Female,Medium,Healthy,21.9,210.0,1.3,8.7,10170,1671,65.0,1.3,3.3,Low,3.0
9997,57,Male,Low,Average,32.9,227.0,2.8,14.0,1000,1592,89.0,1.7,2.8,High,1.6
9998,64,Female,Low,Average,18.4,222.0,2.3,7.3,4206,1429,65.0,2.2,4.0,Medium,1.4
9999,32,Female,Low,Average,20.0,197.0,1.6,8.7,2746,1240,68.0,1.4,3.4,Medium,1.9

In [42]:
df.daily_stress_level.value_counts()

daily_stress_level
Low       5789
Medium    3786
High       425
Name: count, dtype: int64

In [43]:
df.isna().sum()
df.dropna(axis=0, inplace=True)

In [45]:
df.describe()

,age,bmi,caffeine_intake_mg,water_intake_liters,screen_time_hours,daily_steps,calories_burned,resting_heart_rate,deep_sleep_hours,sleep_quality_score,sleep_deviation
count,9198.000000,9198.000000,9198.000000,9198.000000,9198.000000,9198.000000,9198.000000,9198.000000,9198.000000,9198.000000,9198.000000
mean,43.529572,25.091868,207.511633,2.503479,7.060894,7960.098717,1573.632420,66.935529,1.750304,4.169765,1.155708
std,14.911925,3.903476,137.722043,0.800594,2.446780,4019.515237,319.993567,8.440679,0.468285,0.913649,0.757709
min,18.000000,17.500000,0.000000,0.500000,2.000000,1000.000000,491.000000,50.000000,0.700000,1.000000,0.000000
25%,31.000000,22.300000,101.000000,2.000000,5.300000,4911.250000,1353.250000,61.000000,1.400000,3.500000,0.500000
50%,43.000000,25.100000,202.000000,2.500000,7.100000,7390.000000,1560.000000,67.000000,1.700000,4.200000,1.100000
75%,56.000000,27.800000,303.000000,3.000000,8.700000,10126.500000,1785.000000,73.000000,2.100000,4.800000,1.700000
max,69.000000,38.000000,730.000000,5.000000,14.000000,23451.000000,2901.000000,95.000000,3.400000,7.500000,4.200000

In [ ]:
df.to_csv('app/data/reSS.csv', index=False)